version: '3.8'

services:
  api:
    image: openjdk:17-jdk-slim
    build: .
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "api-0.0.1-SNAPSHOT.jar"]
